Repository VidhiBhatt01/The-Frontend-Store, pull requests merged in 2022-10, with the labels that each got.

#5 Added Calculator Project
  Project/Calculator/calculator.css
  Project/Calculator/index.html
  Project/Calculator/script.js
  Project/Calculator/style.css
Labels: hacktoberfest, changes requested

#6 Added Jump and Dodge game
  Games/Jump-&-Dodge_AnimeGame/images/24152.png
  Games/Jump-&-Dodge_AnimeGame/images/3.png
  Games/Jump-&-Dodge_AnimeGame/images/Beyblade-Metal-Fusion-Wallpaper.png
  Games/Jump-&-Dodge_AnimeGame/images/Screenshot (439).png
  Games/Jump-&-Dodge_AnimeGame/images/cloud.png
  Games/Jump-&-Dodge_AnimeGame/images/f2e02c663393bb60e0abc671f864f2f5.png
  Games/Jump-&-Dodge_AnimeGame/images/favicon_b.ico
  Games/Jump-&-Dodge_AnimeGame/images/how2BtbjjDpofnaa2cyKeG.jpg
  Games/Jump-&-Dodge_AnimeGame/images/main.png
  Games/Jump-&-Dodge_AnimeGame/index.html
  Games/Jump-&-Dodge_AnimeGame/script.js
  Games/Jump-&-Dodge_AnimeGame/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#10 Added To-Do-List-App
  Projects/To-do-list/index.html
  Projects/To-do-list/script.js
  Projects/To-do-list/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#19 Password Generator
  Projects/Password-Generator/index.html
  Projects/Password-Generator/script.js
  Projects/Password-Generator/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#25 Contributing Section in README
  CONTRIBUTING.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#21 Add Netflix Clone
  Clones/Netflix Clone/.firebase/hosting.YnVpbGQ.cache
  Clones/Netflix Clone/.firebaserc
  Clones/Netflix Clone/.gitignore
  Clones/Netflix Clone/README.md
  Clones/Netflix Clone/firebase.json
  Clones/Netflix Clone/package-lock.json
  Clones/Netflix Clone/package.json
  Clones/Netflix Clone/public/favicon.ico
  Clones/Netflix Clone/public/index.html
  Clones/Netflix Clone/public/manifest.json
  Clones/Netflix Clone/public/robots.txt
  Clones/Netflix Clone/src/App.css
  Clones/Netflix Clone/src/App.js
  Clones/Netflix Clone/src/Banner.css
  Clones/Netflix Clone/src/Banner.js
  Clones/Netflix Clone/src/Navbar.css
  Clones/Netflix Clone/src/Navbar.js
  Clones/Netflix Clone/src/Requests.js
  Clones/Netflix Clone/src/Row.css
  Clones/Netflix Clone/src/Row.js
  Clones/Netflix Clone/src/app/store.js
  Clones/Netflix Clone/src/axios.js
  Clones/Netflix Clone/src/features/counter/Counter.js
  Clones/Netflix Clone/src/features/counter/Counter.module.css
  Clones/Netflix Clone/src/features/counter/userAPI.js
  Clones/Netflix Clone/src/features/counter/userSlice.js
  Clones/Netflix Clone/src/features/counter/userSlice.spec.js
  Clones/Netflix Clone/src/firebase.js
  Clones/Netflix Clone/src/index.css
  Clones/Netflix Clone/src/index.js
  Clones/Netflix Clone/src/pages/HomeScreen.css
  Clones/Netflix Clone/src/pages/HomeScreen.js
  Clones/Netflix Clone/src/pages/LoginScreen.css
  Clones/Netflix Clone/src/pages/LoginScreen.js
  Clones/Netflix Clone/src/pages/ProfileScreen.css
  Clones/Netflix Clone/src/pages/ProfileScreen.js
  Clones/Netflix Clone/src/pages/SignUpScreen.css
  Clones/Netflix Clone/src/pages/SignUpScreen.js
  Clones/Netflix Clone/src/serviceWorker.js
Labels: hacktoberfest, changes requested

#29 WHAC-A-MOLE game files added
  Games/Whac-a-mole/app.js
  Games/Whac-a-mole/index.html
  Games/Whac-a-mole/mole.jpg
  Games/Whac-a-mole/styles.css
Labels: hacktoberfest, changes requested

#38 TestMemory
  Games/TestMemoryGame/blank.png
  Games/TestMemoryGame/cheeseburger.png
  Games/TestMemoryGame/fries.png
  Games/TestMemoryGame/hotdog.png
  Games/TestMemoryGame/ice-cream.png
  Games/TestMemoryGame/index.html
  Games/TestMemoryGame/index.js
  Games/TestMemoryGame/milkshake.png
  Games/TestMemoryGame/pizza.png
  Games/TestMemoryGame/style.css
  Games/TestMemoryGame/white.png
Labels: question, hacktoberfest

#44 Analog clock
  Projects/Analog clock/index.html
  Projects/Analog clock/script.js
  Projects/Analog clock/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#48 Food Menu Website
  Projects/Food Menu website/images/card-img-1.png
  Projects/Food Menu website/images/card-img-2.png
  Projects/Food Menu website/images/card-img-3.png
  Projects/Food Menu website/images/gallery-img-1.jpg
  Projects/Food Menu website/images/gallery-img-2.jpg
  Projects/Food Menu website/images/gallery-img-3.jpg
  Projects/Food Menu website/images/gallery-img-4.jpg
  Projects/Food Menu website/images/gallery-img-5.jpg
  Projects/Food Menu website/images/gallery-img-6.jpg
  Projects/Food Menu website/index.html
  Projects/Food Menu website/script.js
  Projects/Food Menu website/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#52 Finger print loader
  Projects/FingerPrint Loader/README.md
  Projects/FingerPrint Loader/index.html
  Projects/FingerPrint Loader/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#34 Book Store Website
  Projects/Book Store/README.md
  Projects/Book Store/SearchString.js
  Projects/Book Store/books/AliceInWonderland.txt
  Projects/Book Store/books/JekyllAndHyde.txt
  Projects/Book Store/books/LOTR.txt
  Projects/Book Store/index.html
  Projects/Book Store/style.css
Labels: hacktoberfest, changes requested

#36 Breakout-Classic-game
  Games/Breakout clasic/ball.js
  Games/Breakout clasic/brick.js
  Games/Breakout clasic/index.html
  Games/Breakout clasic/paddle.js
  Games/Breakout clasic/readme.md
Labels: hacktoberfest, hacktoberfest-accepted

#49 Architecture & Interior Design
  Projects/Architect website/images/bg.jpg
  Projects/Architect website/images/contact-bg.jpg
  Projects/Architect website/images/house.png
  Projects/Architect website/images/person-1.jpg
  Projects/Architect website/images/person-2.jpg
  Projects/Architect website/images/person-3.jpg
  Projects/Architect website/index.html
  Projects/Architect website/script.js
  Projects/Architect website/style.css
  Projects/Architect website/tilt.js
Labels: hacktoberfest

#53 basket ball animation
  Projects/basket ball animation/README.md
  Projects/basket ball animation/index.html
  Projects/basket ball animation/style.css
Labels: hacktoberfest

#55 Added uber clone to clone folder.
  Clones/uber-cloned-app/.eslintrc.json
  Clones/uber-cloned-app/.gitignore
  Clones/uber-cloned-app/README.md
  Clones/uber-cloned-app/data/carList.js
  Clones/uber-cloned-app/firebase.js
  Clones/uber-cloned-app/next.config.js
  Clones/uber-cloned-app/package-lock.json
  Clones/uber-cloned-app/package.json
  Clones/uber-cloned-app/pages/_app.js
  Clones/uber-cloned-app/pages/api/hello.js
  Clones/uber-cloned-app/pages/components/Map.js
  Clones/uber-cloned-app/pages/components/RideSelector.js
  Clones/uber-cloned-app/pages/confirm.js
  Clones/uber-cloned-app/pages/index.js
  Clones/uber-cloned-app/pages/login.js
  Clones/uber-cloned-app/pages/search.js
  Clones/uber-cloned-app/plan.md
  Clones/uber-cloned-app/postcss.config.js
  Clones/uber-cloned-app/public/favicon.ico
  Clones/uber-cloned-app/public/vercel.svg
  Clones/uber-cloned-app/styles/Home.module.css
  Clones/uber-cloned-app/styles/globals.css
  Clones/uber-cloned-app/tailwind.config.js
Labels: hacktoberfest, hacktoberfest-accepted

#59 Speed Typing
  Games/Speed Typing/index.html
  Games/Speed Typing/script.js
  Games/Speed Typing/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#61 Issue #50: adding a dictionary app
  Projects/Dictionary/index.html
  Projects/Dictionary/script.js
  Projects/Dictionary/style.css
Labels: hacktoberfest, changes requested

#64 Added wordle clone
  Clones/Wordle Clone/index.html
  Clones/Wordle Clone/main.js
  Clones/Wordle Clone/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#78 An Insect Catching game
  Games/Catch an Insect/app.js
  Games/Catch an Insect/index.html
  Games/Catch an Insect/styles.css
Labels: hacktoberfest

#80 Added dino game
  Games/Dino-Game/assets/block.png
  Games/Dino-Game/assets/cloud.jpg
  Games/Dino-Game/assets/dino.png
  Games/Dino-Game/assets/road.png
  Games/Dino-Game/index.html
  Games/Dino-Game/main.js
  Games/Dino-Game/style.css
Labels: hacktoberfest, changes requested

#84 Contact Form Template
  Projects/Contact form template/index.html
  Projects/Contact form template/style.css
Labels: hacktoberfest, changes requested
