Repository VidhiBhatt01/The-Frontend-Store, pull requests merged in 2023-10, with the labels that each got.

#97 Create Water Snake Gun Game
  Games/water snake gun game/Computer.jpg
  Games/water snake gun game/User.jpeg
  Games/water snake gun game/gun.jpg
  Games/water snake gun game/index.html
  Games/water snake gun game/script.js
  Games/water snake gun game/snake.jpg
  Games/water snake gun game/styles.css
  Games/water snake gun game/water.jpg
Labels: hacktoberfest, hacktoberfest-accepted

#93 Instagram clone for hacktoberfest
  Clones/Instagram-Clone/.prettierrc
  Clones/Instagram-Clone/assets/default-user.png
  Clones/Instagram-Clone/assets/favicon.svg
  Clones/Instagram-Clone/assets/icon/add.svg
  Clones/Instagram-Clone/assets/icon/bookmark.svg
  Clones/Instagram-Clone/assets/icon/comment.svg
  Clones/Instagram-Clone/assets/icon/heart.svg
  Clones/Instagram-Clone/assets/icon/home.svg
  Clones/Instagram-Clone/assets/icon/messenger.svg
  Clones/Instagram-Clone/assets/icon/more.svg
  Clones/Instagram-Clone/assets/icon/reels.svg
  Clones/Instagram-Clone/assets/icon/search.svg
  Clones/Instagram-Clone/assets/icon/share.svg
  Clones/Instagram-Clone/assets/icon/shop.svg
  Clones/Instagram-Clone/assets/insta-clone.png
  Clones/Instagram-Clone/assets/logo.svg
  Clones/Instagram-Clone/index.html
  Clones/Instagram-Clone/script.js
  Clones/Instagram-Clone/style.css
Labels: hacktoberfest, changes requested

#102 PR : QR Code Generator
  Projects/QR Code Generator/README.md
  Projects/QR Code Generator/index.html
  Projects/QR Code Generator/qrcode.png
  Projects/QR Code Generator/script.js
  Projects/QR Code Generator/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#104 car game ,SEESAW game and Periodic table added
  Games/Car_game/car.png
  Games/Car_game/car2.jpg
  Games/Car_game/race.css
  Games/Car_game/race.html
  Games/SeeSaw Game/index.html
  Games/SeeSaw Game/script.js
  Games/SeeSaw Game/styles.css
  Projects/Periodic Table/periodic.py
Labels: hacktoberfest, hacktoberfest-accepted

#103 Created a AI Image Generator Using HTML-CSS-JS
  Projects/AI Image Generator Website/images/bg.jpg
  Projects/AI Image Generator Website/images/download.svg
  Projects/AI Image Generator Website/images/img-1.jpg
  Projects/AI Image Generator Website/images/img-2.jpg
  Projects/AI Image Generator Website/images/img-3.jpg
  Projects/AI Image Generator Website/images/img-4.jpg
  Projects/AI Image Generator Website/images/loader.svg
  Projects/AI Image Generator Website/index.html
  Projects/AI Image Generator Website/script.js
  Projects/AI Image Generator Website/style.css
Labels: hacktoberfest

#107 Added a 3D Chessboard Using Python
  Projects/Visualize a 3D chessborad in Python/chessboard.py
  Projects/Visualize a 3D chessborad in Python/images/VCB-1.png
  Projects/Visualize a 3D chessborad in Python/images/VCB-3.png
  Projects/Visualize a 3D chessborad in Python/images/VSB-2.png
Labels: hacktoberfest, hacktoberfest-accepted

#110 adding myntra-clone
  Clones/myntra-clone/Common Files/corousel.js
  Clones/myntra-clone/Common Files/headerMenu.js
  Clones/myntra-clone/Common Files/homeLiving.css
  Clones/myntra-clone/Common Files/homeLiving.js
  Clones/myntra-clone/Common Files/hyperlinks.js
  Clones/myntra-clone/Common Files/image/favicon.png
  Clones/myntra-clone/Common Files/image/myntra-removebg-preview.png
  Clones/myntra-clone/Common Files/men.js
  Clones/myntra-clone/Common Files/style.css
  Clones/myntra-clone/Common Files/women.js
  Clones/myntra-clone/Home Living Products/home_furnishing.css
  Clones/myntra-clone/Home Living Products/home_furnishing.html
  Clones/myntra-clone/Home Living Products/home_furnishing.js
  Clones/myntra-clone/Homepages/homeLiving.html
  Clones/myntra-clone/Homepages/menHomePage.html
  Clones/myntra-clone/Homepages/womenHomePage.html
  Clones/myntra-clone/Landingpage/deals.js
  Clones/myntra-clone/Landingpage/footer.css
  Clones/myntra-clone/Landingpage/header.css
  Clones/myntra-clone/Landingpage/index.html
  Clones/myntra-clone/Landingpage/navbar.css
  Clones/myntra-clone/Profile/profile.css
  Clones/myntra-clone/Profile/profile.html
  Clones/myntra-clone/Profile/profile.js
  Clones/myntra-clone/Profile/signup.html
  Clones/myntra-clone/Profile/signup.js
  Clones/myntra-clone/README.md
  Clones/myntra-clone/menspage/mens.css
  Clones/myntra-clone/menspage/mens.html
  Clones/myntra-clone/menspage/mens.js
  Clones/myntra-clone/payment/address.css
  Clones/myntra-clone/payment/address.html
  Clones/myntra-clone/payment/confetti.js
  Clones/myntra-clone/payment/end.css
  Clones/myntra-clone/payment/end.html
  Clones/myntra-clone/payment/otp.css
  Clones/myntra-clone/payment/otp.html
  Clones/myntra-clone/payment/payment.css
  Clones/myntra-clone/payment/payment.html
  Clones/myntra-clone/wishlist/cart.css
  Clones/myntra-clone/wishlist/cart.html
  Clones/myntra-clone/wishlist/cart.js
  Clones/myntra-clone/wishlist/wishlist.css
  Clones/myntra-clone/wishlist/wishlist.html
  Clones/myntra-clone/wishlist/wishlist.js
  Clones/myntra-clone/womensdata/style&js/womens.js
  Clones/myntra-clone/womensdata/style&js/womestyle.css
  Clones/myntra-clone/womensdata/women.html
Labels: hacktoberfest, hacktoberfest-accepted

#112 Adding WordCounter project to the repository. [Hacktoberfest]
  Projects/WordCounter/main1.html
  Projects/WordCounter/main1.js
  Projects/WordCounter/main2.html
  Projects/WordCounter/main2.js
  Projects/WordCounter/main3.html
  Projects/WordCounter/main4.html
  Projects/WordCounter/readme.md
  Projects/WordCounter/style1.css
  Projects/WordCounter/style2.css
  Projects/WordCounter/style3.css
Labels: hacktoberfest, hacktoberfest-accepted

#115 Addded antonyms search web app
  Projects/ANTONYMS SEARCH WEB APPLICATION/Images/pic1.png
  Projects/ANTONYMS SEARCH WEB APPLICATION/Images/pic2.png
  Projects/ANTONYMS SEARCH WEB APPLICATION/index.html
  Projects/ANTONYMS SEARCH WEB APPLICATION/script.js
  Projects/ANTONYMS SEARCH WEB APPLICATION/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#117 Added Invisible Cloak Using OpenCV
  Projects/Invisible_Cloak/Images/pic1.png
  Projects/Invisible_Cloak/background.py
  Projects/Invisible_Cloak/invisible_cloak.py
Labels: hacktoberfest, changes requested

#120 Restaurant website added
  Projects/Restaurant/index.html
Labels: hacktoberfest, changes requested
